name: wgs_cg_stlfr
channels:
- conda-forge
- defaults
- bioconda
- biocore
dependencies:
- python==3.6.6
- appdirs==1.4.3
- bio==0.1.0
- biopython==1.76
- certifi==2018.11.29
- chardet==3.0.4
- ConfigArgParse==0.13.0
- datrie==0.7.1
- decorator==4.4.2
- docopt==0.6.2
- docutils==0.14
- extremevariantfilter==0.0a4
- gitdb2==2.0.5
- GitPython==2.1.11
- graphviz==0.10.1
- idna==2.8
- Jinja2==2.11.2
- jsonschema==2.6.0
- MarkupSafe==1.1.1
- networkx==2.4
- numpy==1.15.4
- pandas==0.23.4
- psutil==5.6.7
- pysam==0.15.2
- python-dateutil==2.7.5
- pytz==2018.7
- PyYAML==3.13
- ratelimiter==1.2.0.post0
- requests==2.21.0
- scikit-learn==0.20.2
- scipy==1.2.0
- six==1.12.0
- smmap2==2.0.5
- snakemake==5.3.1
- urllib3==1.24.1
- wrapt==1.10.11
- xgboost==0.81
- yappi==1.2.3
- r-base=3.2.1
